  ############################################################################
  ## 
  ##  Makefile.linux  
  ## 
  ##
  ##  AgentX++ 2
  ##  -------------------------------------
  ##  Copyright (C) 2000-2013 - Frank Fock
  ##  
  ##  Use of this software is subject to the license agreement you received
  ##  with this software and which can be downloaded from 
  ##  http:/www.agentpp.com
  ##
  ##  This is licensed software and may not be used in a commercial
  ##  environment, except for evaluation purposes, unless a valid
  ##  license has been purchased.
  ##  
  ##########################################################################*





CFLAGS	        = -g -Wall $(AGENTPPOPTIONS)
SHARED		= -fPIC -shared
CLINK		= -c -o
CC              = cc
CPP             = g++ #-static

RM              = rm -f 

include common.mk
